import Card from "@/custom-components/Card";
import Spinner from "@/custom-components/Spinner";
import { useSelector } from "react-redux";
import { Link, useSearchParams } from "react-router-dom";
import { toast } from "react-toastify";

const statusOf = (auction) => new Date(auction.startTime) > new Date() ? "upcoming" : new Date(auction.endTime) < new Date() ? "ended" : "active";
const Auctions = () => {
  const { allAuctions, loading, usingDemoData } = useSelector((state) => state.auction); const [params, setParams] = useSearchParams();
  const filters = { q: params.get("q") || "", category: params.get("category") || "", status: params.get("status") || "", sort: params.get("sort") || "newest", maxPrice: params.get("maxPrice") || "" };
  const update = (event) => { const next = new URLSearchParams(params); const { name, value } = event.target; value ? next.set(name, value) : next.delete(name); setParams(next); };
  const saveSearch = () => { const saved = JSON.parse(localStorage.getItem("bidspirit-saved-searches") || "[]"); localStorage.setItem("bidspirit-saved-searches", JSON.stringify([...saved, { ...filters, savedAt: new Date().toISOString() }])); toast.success("Search alert saved locally (demo mode)."); };
  const categories = [...new Set(allAuctions.map((item) => item.category).filter(Boolean))].sort();
  let auctions = allAuctions.filter((auction) => (!filters.q || [auction.title, auction.category, auction.description].some((value) => value?.toLowerCase().includes(filters.q.toLowerCase()))) && (!filters.category || auction.category === filters.category) && (!filters.status || statusOf(auction) === filters.status) && (!filters.maxPrice || Number(auction.startingBid) <= Number(filters.maxPrice)));
  auctions = [...auctions].sort({ newest: (a, b) => new Date(b.createdAt || 0) - new Date(a.createdAt || 0), ending: (a, b) => new Date(a.endTime) - new Date(b.endTime), price_low: (a, b) => a.startingBid - b.startingBid, price_high: (a, b) => b.startingBid - a.startingBid }[filters.sort]);
  if (loading) return <Spinner />;
  return <main className="mx-auto min-h-[calc(100vh-16rem)] w-full max-w-7xl px-4 py-10 sm:px-6 lg:py-14"><Link to="/" className="inline-flex text-sm font-semibold text-amber-700 hover:text-amber-800">Back to home</Link><header className="mt-5"><p className="text-sm font-semibold uppercase tracking-wide text-amber-700">Auction catalogue</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Auctions</h1><p className="mt-2 text-slate-600">Search lots, compare estimates, and follow live, upcoming, or completed sales.</p></header>{usingDemoData && <div className="mt-5 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Offline demo catalogue:</strong> these BidSpirit samples are inspired by public auction themes—not Abell inventory or live sales.</div>}<form className="mt-7 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-5"><input name="q" value={filters.q} onChange={update} className="input-field lg:col-span-2" placeholder="Search title, category, or description..."/><select name="category" value={filters.category} onChange={update} className="input-field"><option value="">All categories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select><select name="status" value={filters.status} onChange={update} className="input-field"><option value="">All statuses</option><option value="active">Live now</option><option value="upcoming">Upcoming</option><option value="ended">Past results</option></select><select name="sort" value={filters.sort} onChange={update} className="input-field"><option value="newest">Newest first</option><option value="ending">Ending soon</option><option value="price_low">Starting bid: low</option><option value="price_high">Starting bid: high</option></select><input name="maxPrice" type="number" min="0" value={filters.maxPrice} onChange={update} className="input-field" placeholder="Maximum starting bid"/><button type="button" onClick={saveSearch} className="rounded-md border border-amber-700 px-3 py-2 text-sm font-semibold text-amber-800 hover:bg-amber-50">Save search alert</button><Link to="/auctions" className="self-center text-center text-sm font-semibold text-amber-700 hover:text-amber-800">Clear filters</Link></form><p className="mt-5 text-sm text-slate-600"><strong>{auctions.length}</strong> catalogue items</p>{auctions.length ? <div className="mt-5 flex flex-wrap gap-6">{auctions.map((auction) => <Card key={auction._id} title={auction.title} startTime={auction.startTime} endTime={auction.endTime} imgSrc={auction.image?.url} startingBid={auction.startingBid} id={auction._id}/>)}</div> : <section className="mt-6 rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="text-xl font-bold">No catalogue items match</h2><p className="mt-2 text-slate-600">Clear filters or try a different keyword.</p></section>}</main>;
};
export default Auctions;
