import { useState } from "react";
import { toast } from "react-toastify";

const tasks = ["Maximum / absentee bid", "Phone bidding request", "Pickup appointment", "Shipping quote", "Email & SMS preferences", "Seller consignment timeline", "Auctioneer live-sale console"];
const read = () => JSON.parse(localStorage.getItem("bidspirit-demo-services") || "[]");

const AuctionServices = () => {
  const [active, setActive] = useState(tasks[0]); const [records, setRecords] = useState(read); const [form, setForm] = useState({ lot: "", amount: "", contact: "", date: "", notes: "" });
  const update = (event) => setForm((value) => ({ ...value, [event.target.name]: event.target.value }));
  const submit = (event) => { event.preventDefault(); const record = { id: crypto.randomUUID(), type: active, ...form, status: active === "Auctioneer live-sale console" ? "sale open" : "received", createdAt: new Date().toLocaleString() }; const next = [record, ...records]; localStorage.setItem("bidspirit-demo-services", JSON.stringify(next)); setRecords(next); setForm({ lot: "", amount: "", contact: "", date: "", notes: "" }); toast.success("Demo request saved locally."); };
  return <main className="mx-auto min-h-[calc(100vh-14rem)] max-w-6xl px-4 py-10 sm:px-6"><p className="text-sm font-semibold uppercase tracking-wide text-amber-700">Demo operations</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">Auction service desk</h1><p className="mt-3 max-w-3xl text-slate-600">Offline prototype only. Requests stay in this browser and do not contact staff, carriers, banks, or bidders.</p><div className="mt-6 rounded-lg border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><strong>Demo mode:</strong> no real bid, payment, shipping, message, or appointment is created here.</div><div className="mt-7 grid gap-6 lg:grid-cols-[15rem_1fr]"><nav className="flex gap-2 overflow-x-auto lg:flex-col">{tasks.map((item) => <button key={item} onClick={() => setActive(item)} className={`shrink-0 rounded-md px-4 py-3 text-left text-sm font-semibold ${active === item ? "bg-primary text-white" : "border border-slate-200 bg-white text-slate-700 hover:bg-slate-50"}`}>{item}</button>)}</nav><section className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">{active}</h2><p className="mt-2 text-sm text-slate-600">{description(active)}</p>{active === "Seller consignment timeline" ? <Timeline /> : active === "Auctioneer live-sale console" ? <LiveConsole /> : <form onSubmit={submit} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Lot reference" name="lot" value={form.lot} onChange={update} required/><Field label={active.includes("bid") ? "Maximum bid (LKR)" : active.includes("Shipping") ? "Destination" : "Contact preference"} name="amount" value={form.amount} onChange={update} required/><Field label="Email or phone" name="contact" value={form.contact} onChange={update} required/><Field label={active.includes("Pickup") ? "Preferred date/time" : "Optional date"} name="date" type={active.includes("Pickup") ? "datetime-local" : "text"} value={form.date} onChange={update}/><div className="sm:col-span-2"><label className="form-label" htmlFor="notes">Notes</label><textarea id="notes" name="notes" value={form.notes} onChange={update} rows="4" className="input-field" placeholder="Optional details"/></div><button className="w-fit rounded-md bg-amber-700 px-5 py-3 font-semibold text-white hover:bg-amber-800">Save demo request</button></form>}</section></div><section className="mt-8"><h2 className="text-xl font-bold">Saved demo activity</h2><div className="mt-4 space-y-3">{records.length ? records.map((record) => <article key={record.id} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{record.type}</strong><span className="capitalize text-amber-800">{record.status}</span></div><p className="mt-1 text-sm text-slate-600">Lot: {record.lot || "not specified"} · {record.createdAt}</p></article>) : <p className="text-slate-600">No demo activity saved.</p>}</div></section></main>;
};
const description = (type) => ({ "Maximum / absentee bid": "Store a maximum amount for an auctioneer to execute up to during a sale.", "Phone bidding request": "Request a staff call before a scheduled sale.", "Pickup appointment": "Request an item collection time after a completed payment.", "Shipping quote": "Request a mock transport estimate and delivery guidance.", "Email & SMS preferences": "Choose which sale reminders and account updates you would like to receive.", "Seller consignment timeline": "Preview the stages from valuation to listing, sale, and settlement.", "Auctioneer live-sale console": "Preview a sale-control interface; it cannot accept or settle real bids." }[type]);
const Field = ({ label, ...props }) => <div><label className="form-label" htmlFor={props.name}>{label}</label><input id={props.name} className="input-field" {...props}/></div>;
const Timeline = () => <ol className="mt-6 space-y-3">{["Valuation request received", "Specialist review", "Consignment accepted", "Catalogue and condition report", "Auction published", "Sale completed", "Payment and delivery settlement"].map((step, index) => <li key={step} className="flex gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-amber-100 text-sm font-bold text-amber-800">{index + 1}</span><span className="pt-1 text-slate-700">{step}</span></li>)}</ol>;
const LiveConsole = () => <div className="mt-6 rounded-lg bg-slate-950 p-5 text-white"><p className="text-sm text-emerald-200">DEMO LIVE SALE</p><h3 className="mt-1 text-2xl font-bold">Lot 101 · Current bid LKR 325,000</h3><div className="mt-5 flex flex-wrap gap-3"><button onClick={() => toast.info("Demo bid increment recorded visually only.")} className="rounded-md bg-amber-600 px-4 py-3 font-semibold">+ LKR 5,000</button><button onClick={() => toast.info("Demo hammer action recorded visually only.")} className="rounded-md border border-white/40 px-4 py-3 font-semibold">Hammer sold</button></div></div>;
export default AuctionServices;
