import { useState } from "react";
import { useNavigate, Link } from "react-router-dom";
import emailjs from "@emailjs/browser";
import { toast } from "react-toastify";
import PropTypes from "prop-types";
const Contact = () => { const [form, setForm] = useState({name:"",email:"",phone:"",subject:"",message:""}); const [loading, setLoading] = useState(false); const navigate = useNavigate(); const update=(event)=>setForm((current)=>({...current,[event.target.name]:event.target.value})); const submit=(event)=>{event.preventDefault(); setLoading(true); emailjs.send("service_rv32bis","template_ekdhy8i",form,"o4D33tqxJtE92Lmqs").then(()=>{toast.success("Your message has been sent.");navigate("/");}).catch(()=>toast.error("Unable to send your message. Please try again.")).finally(()=>setLoading(false));}; return <main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 lg:py-14"><Link to="/" className="text-sm font-semibold text-amber-700 hover:text-amber-800">← Back to home</Link><div className="mt-6 grid gap-8 lg:grid-cols-[.75fr_1.25fr]"><section><p className="text-sm font-semibold uppercase tracking-wide text-amber-700">Support</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-slate-950">Contact us</h1><p className="mt-4 leading-7 text-slate-600">Tell us how we can help. Include enough detail for our team to respond effectively.</p></section><form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><Field label="Your name" name="name" value={form.name} onChange={update} autoComplete="name" required /><Field label="Email" name="email" type="email" value={form.email} onChange={update} autoComplete="email" spellCheck={false} required /><Field label="Phone" name="phone" type="tel" value={form.phone} onChange={update} autoComplete="tel" inputMode="tel" required /><Field label="Subject" name="subject" value={form.subject} onChange={update} autoComplete="off" required /></div><div className="mt-5"><label htmlFor="contact-message" className="form-label">Message</label><textarea id="contact-message" name="message" value={form.message} onChange={update} rows="7" className="input-field" autoComplete="off" required /></div><button type="submit" disabled={loading} className="mt-6 rounded-md bg-amber-700 px-5 py-3 font-semibold text-white hover:bg-amber-800 disabled:bg-amber-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600 focus-visible:ring-offset-2">{loading ? "Sending Message…" : "Send Message"}</button></form></div></main>; };
const Field=({label,name,type="text",...props})=><div><label htmlFor={`contact-${name}`} className="form-label">{label}</label><input id={`contact-${name}`} name={name} type={type} className="input-field" {...props}/></div>;
Field.propTypes={label:PropTypes.string.isRequired,name:PropTypes.string.isRequired,type:PropTypes.string};
export default Contact;
