import { postCommissionProof } from "@/store/slices/commissionSlice";
import { useId, useState } from "react";
import { useDispatch, useSelector } from "react-redux";

const SubmitCommission = () => {
  const [proof, setProof] = useState(null); const [amount, setAmount] = useState(""); const [comment, setComment] = useState("");
  const dispatch = useDispatch(); const { loading } = useSelector((state) => state.commission); const proofId = useId();
  const submit = (event) => { event.preventDefault(); if (!proof) return; const data = new FormData(); data.append("proof", proof); data.append("amount", amount); data.append("comment", comment); dispatch(postCommissionProof(data)); };
  return <section className="mx-auto min-h-screen w-full max-w-3xl px-4 py-10 sm:px-6"><div className="mb-7"><p className="text-sm font-semibold uppercase tracking-wide text-amber-700">Auctioneer workspace</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Submit a payment proof</h1><p className="mt-2 text-slate-600">Upload a clear payment record for review.</p></div><form onSubmit={submit} className="rounded-xl border border-slate-200 bg-white p-5 sm:p-8"><div className="space-y-5"><div><label htmlFor="commission-amount" className="form-label">Amount paid</label><input id="commission-amount" name="amount" type="number" min="0.01" step="0.01" inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} className="input-field" required /></div><div><label htmlFor={proofId} className="form-label">Payment proof</label><input id={proofId} name="proof" type="file" accept="image/png,image/jpeg,image/webp" onChange={(e) => setProof(e.target.files?.[0] || null)} className="file-input block w-full rounded-md border border-slate-300 p-2" required /><p className="mt-2 text-sm text-slate-500">PNG, JPEG, or WebP only.</p></div><div><label htmlFor="commission-comment" className="form-label">Comment</label><textarea id="commission-comment" name="comment" rows="6" value={comment} onChange={(e) => setComment(e.target.value)} className="input-field" autoComplete="off" required /></div></div><button type="submit" disabled={loading} className="mt-7 rounded-md bg-amber-700 px-5 py-3 font-semibold text-white hover:bg-amber-800 disabled:cursor-not-allowed disabled:bg-amber-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-600 focus-visible:ring-offset-2">{loading ? "Uploading…" : "Upload Payment Proof"}</button></form></section>;
};
export default SubmitCommission;
